- hosts: localhost
  vars:
    source_key: "./.ssh/id_1"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_1"
    personal: "{{ lookup('env', 'HOME') }}/personal"
  pre_tasks:
    - name: Update cache
      become: true
      apt:
        force_apt_get: true
        update_cache: true
  tasks: 
    - include: tasks/ssh.yml
    - include: tasks/zsh.yml
    - include: tasks/node.yml
